repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  
  # NOTE: Pyright is kind of janky
  # - repo: https://github.com/RobertCraigie/pyright-python
  #   rev: v1.1.358
  #   hooks:
  #   - id: pyright